import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";

const geistSans = Nunito({
  variable: "--font-nunito",
  subsets: ["cyrillic"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} antialiased`}
      >
      <div className="px-20 py-10">
          {children}
      </div>
      </body>
    </html>
  );
}
